openapi: 3.0.1
info:
  title: HRIS
  version: v1
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /value/GetEmployeeDetailWithAdditionalFromLegalEntityNLastUpdateDate:
    get:
      parameters:
       -
        name: legalEntityId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
       -
        name: lastUpdatedDate
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
       -
        name: Ocp-Apim-Subscription-Key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
x-wso2-api-key-header: ApiKey
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: true
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - Internal-Key
   - Ocp-Apim-Subscription-Key
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - https://mcapseamtsohcmintegprd1.azure-api.net/empout/api
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - https://mcapseamtsohcmintegprd1.azure-api.net/empout/api
  type: http
x-wso2-basePath: /str/sw/v1
x-wso2-transports:
 - http
 - https
x-wso2-application-security:
  security-types:
   - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
